apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: useless-rs
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: useless
  template:
    metadata:
      labels: 
        app: useless
    spec: 
      containers:
      - name: useless
        image: sonambewafaa/useless:yellow
        ports:
          - containerPort: 80
