apiVersion: v1
kind: PersistentVolume
metadata:
  name: pyaar-ka-storage
spec:
  storageClassName: gym-lover
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  azureFile:
    secretName: shadikephotos-ka-creds
    shareName: honeymoon
  capacity: 
    storage: 4Gi