apiVersion: v1
kind: PersistentVolume
metadata:
  name: pyaar-ka-storage
spec:
  accessModes: 
  - ReadWriteMany
  azureFile:
    secretName: shadikephotos-ka-creds
    shareName: honeymoon
  capacity: 
    storage: 4Gi